[workspace]
members = [
    "./src/app",
    "./src/domain/todo-model",
    "./src/domain/todo-usecase",
    "./src/gateway/rdb",
]
exclude = ["./migration"]

[workspace.dependencies]
thiserror = "1.0.53"
chrono = "0.4.26"
serde = "1.0.193"
serde_json = "1.0.109"
async-trait = "0.1.76"
