[package]
name = "todo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
sea-orm = {version = "0.12.2", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}
uuid = {version = "1.4.1", features = ["v4"]}
